### PR TITLE
Hello, Clojurescript Track!

### PR DESCRIPTION
**Pull request by LeaveNhA**
Added Hello World exercise for to be the water of life.

### CODE REVIEW

**Comment by iHiD** [comment]
@LeaveNhA You probably want to configure your GitHub and git so that they have the same email, so that your commits appear with your name/photo etc :)

**Comment by iHiD** [comment]
@kotp @nobbz Would you mind taking a look at this pls?  It's the first clojurescript PR :)

**Comment by LeaveNhA** [comment]
I've changed my photo lastday. 
Is it relevant ?

Thank you for your feedback @iHiD. 😇

**Comment by iHiD** [comment]
Screenshot 2020-08-05 at 13 06 46

@LeaveNhA Seen how the commits aren't associated with your GitHub account. See [this article](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user)  for more details :)

**Comment by LeaveNhA** [comment]
I think, I solved my little Github Account problem @iHiD. 
Thank you for the information. 😇🙏🏻

**Comment by iHiD** [comment]
Great. You probably need to amend your commits to get them to show up here correctly :)

**Comment by LeaveNhA** [comment]
#3 is a yet another first PR from me, but I think it's not containing the Account Problem.

Thank you again! 😇

**Pull request closed without merging**
